# https://hub.docker.com/r/library/node/tags/

image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache

#This declares the pipeline stages
stages:
  - test
  - sonar
  - build

cache:
  paths:
    - node_modules/
    
install-dependencies:
  stage: .pre
  script: npm install

run-unit-test:
  stage: test
  script:
    - npm test -u
    - npm run test:coverage

include:
  - local: ".gitlab-ci-sonar.yml"

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build
