# https://hub.docker.com/r/library/node/tags/

image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache

#This declares the pipeline stages
stages:
  - test
  - build

include:
  - local: ".gitlab-ci-sonar.yml"

cache:
  paths:
    - node_modules/

run-unit-test:
  stage: test
  script:
    - npm install
    - npm test

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build
